### PR TITLE
Framework build out

### PR DESCRIPTION
**Pull request by TedatKentik**
Building framework for automation tasks

### CODE REVIEW

**Review by grrrrreg — COMMENTED** [review]
Can't merge for now because as far as I understand it, the entire onboarding scans this repo and creates device manufacturers on the fly based on what's there.
What will happen if we merge is that we'll see cloud_AWS being offered as a router device manufacturer.
What needs to happen first @TedatKentik is for frontend to be informed to ignore this directory in the device onboarding code - any chance you can ping them about it ? CC @michaeljho

**Comment by TedatKentik** [comment]
Mike Ho, @michaeljho
We are building out a staging area on the Kentik git repo for cloud
automation.  AWS, GCP, Azure, IBM.

I built the folder structure where we will start adding small modules.  Per
guidance from Greg, we need to ignore these.  See comment from Greg below.

**Comment by TedatKentik** [comment]
@grrrrreg @michaeljho @learhy 
This week (tomorrow), we have the first code check in for Terraform automation to build IAM role, S3 bucket, assignment of appropriate role to S3 bucket, configure first (single) VPC to write logs to s3 bucket.  

Later this week, we should receive code check in for multiple VPC to write to S3 bucket.

Next week we should receive code check in for Ansible version of same capabilities.

For these code check in, should we craft a separate repository for Cloud Automation, which is not part of the Kentik code snippets?

something like
https://github.com/kentik/cloud-config-snippets

**Comment by TedatKentik** [comment]
I created an alternate repository to move forward with code check in for Codilime.

This is a private repository that can be shared with Kentik & Codilime.  When we have consensus on how to manage our config-snippets, this can be merged, if desired.
https://github.com/kentik/config-snippets-cloud/

**Comment by jryburn** [comment]
Closing pull request since we decided to put the cloud automation work in a separate repo.

**Pull request closed without merging**
