### PR TITLE
Telemetry configs for juniper and cisco

### PR DESCRIPTION
**Pull request by kagawaa**

### CODE REVIEW

**Comment by kagawaa** [comment]
@i3149 can you look at the https://github.com/kentik/config-snippets/pull/12/files#diff-b6c707b9743cca953db9db96634725e3 XR config. what paths are we really using?

**Comment by i3149** [comment]
We're only using

Cisco-IOS-XR-infra-statsd-oper:infra-statistics/interfaces/interface/latest/
generic-counters

Now.

**Comment by kagawaa** [comment]
thanks. i'm going to delete the rest

**Comment by kagawaa** [comment]
@grrrrreg can you look these over?

**Comment by kagawaa** [comment]
@grrrrreg changes made.

**Pull request merged**
